[package]
name = "sentry-cronwell"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
clap = "2.10"
libc = "0.2"
url = "1.2.0"
base64 = "0.2.0"
curl = "0.3.1"
serde = "0.7.5"
serde_json = "0.7.1"
serde_macros = "0.7.5"
